sudo: true
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - CI=false npm run build


env:
    global:
      - COVERALLS_PARALLEL=true
jobs:
    include:
        - stage: Produce Coverage
    node_js: node
    script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
notifications:
    webhooks: https://coveralls.io/webhook